### ISSUE TITLE
Support Expo SDK 52

### ISSUE THREAD

**Issue by dwightwatson** [prisma/react-native-prisma#45]
I'm not entirely certain what is going on here, but noting it here in case it's not just me. SDK 52 was released today, and after upgrading from 51 to 52 my app will no longer build on EAS.

```
env: load .env
env: export LOGGING_ENABLED
Starting Metro Bundler
iOS Bundling failed 7961ms node_modules/expo-router/entry.js (1446 modules)
Unable to resolve module .prisma/client/react-native from /Users/expo/workingdir/build/node_modules/@prisma/client/react-native.js: .prisma/client/react-native could not be found within the project or in these directories:
  node_modules
  1 | module.exports = {
> 2 |   ...require('.prisma/client/react-native'),
    |               ^
  3 | }
  4 |
Error: Unable to resolve module .prisma/client/react-native from /Users/expo/workingdir/build/node_modules/@prisma/client/react-native.js: .prisma/client/react-native could not be found within the project or in these directories:
  node_modules
  1 | module.exports = {
> 2 |   ...require('.prisma/client/react-native'),
    |               ^
  3 | }
  4 |
Error: Unable to resolve module .prisma/client/react-native from /Users/expo/workingdir/build/node_modules/@prisma/client/react-native.js: .prisma/client/react-native could not be found within the project or in these directories:
  node_modules
  1 | module.exports = {
> 2 |   ...require('.prisma/client/react-native'),
    |               ^
  3 | }
  4 |
    at ModuleResolver.resolveDependency (/Users/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:148:15)
    at DependencyGraph.resolveDependency (/Users/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:235:43)
    at /Users/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:160:21
    at resolveDependencies (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at visit (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 6)
    at visit (/Users/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
npx expo export:embed --eager --platform ios --dev false exited with non-zero code: 1
```

I wonder if it is a change related to bundling in SDK 52, or perhaps some hook/event isn't firing when it previously did.

**Comment by sergiofra98** [comment]
> I'm not entirely certain what is going on here, but noting it here in case it's not just me. SDK 52 was released today, and after upgrading from 51 to 52 my app will no longer build on EAS.

i have this issue too, the curious thing is that it only occurs during compile time, in expo go it works normally.

my target is SDK 34 and the minimum is 24.

I'm running open JDK and JRE 17, Android SDK with plaform and build-tools 35 and NDK 26.

Both local and cloud builds fail.

**Comment by piscopancer** [comment]
+1. Simply trying to do migrations on startup fails with error
```
Android Bundling failed 4099ms C:\dev\mobile\expo\slow\node_modules\expo-router\entry.js (3070 modules)
Unable to resolve ".prisma/client/react-native" from "node_modules\@prisma\client\react-native.js"
```

**Comment by abc-tiago** [comment]
I've tried everything and mine always gives the same error.
I'm trying to use expo 52 react native 0.76 and the version is recent from react-native-prisma

Even starting a project from scratch I can't get the lib to work

**Comment by EugeneGeek** [comment]
Tell me if the transition to version 0.76 of React Native will be implemented? If so, what is the approximate time frame?

**Comment by dwightwatson** [comment]
I've had another go this evening after bumping Expo and updating to `@prisma/client` to 6 and it appears to be working for me now.

```
npx expo install --check
```

Curious to see if this has been resolved for anyone else?

**Comment by florentmsl** [comment]
I can confirm that it still fails. Sadly a dealbreaker for my project since I need to use RN 0.76. Does anyone know about some insights, how much effort it would be to make them compatible?

**Comment by sorenbs** [comment]
We are taking a different approach to fix this and enable support for New Architecture. This involves a deep rearchitecture of Prisma ORM, and will take a while. I wrote it up here: https://github.com/prisma/react-native-prisma/issues/57

**Comment by question429** [comment]
Unable to resolve module .prisma/client/react-native
